# Generated by Django 3.2 on 2021-05-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('audience_ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.group')),
                ('member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Sugession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segession_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SugessionFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sugession_feedback_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('segession_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.sugession')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('audience_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.group')),
                ('audience_ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ministry')),
                ('member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_feedback_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.complaint')),
                ('member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
